---
- hosts: servers
  roles:
    - { role: geerlingguy.docker, tags: [ 'docker' ] , become: yes}
    - { role: common, tags: [ 'common' ] , become: yes}
    - { role: treafik, tags: [ 'treafik' ] }
  gather_facts: no

